import curses

class ClickStatus:
    PRESSED: int = curses.BUTTON1_PRESSED
    RELEASED: int = curses.BUTTON1_RELEASED
    CLICKED: int = curses.BUTTON1_CLICKED
    DOUBLE_CLICKED: int = curses.BUTTON1_DOUBLE_CLICKED
    TRIPLE_CLICKED: int = curses.BUTTON1_TRIPLE_CLICKED
    RIGHT_PRESSED: int = curses.BUTTON2_PRESSED
    RIGHT_CLICKED: int = curses.BUTTON2_CLICKED
    RIGHT_DOUBLE_CLICKED: int = curses.BUTTON2_DOUBLE_CLICKED
    RIGHT_TRIPLE_CLICKED: int = curses.BUTTON2_TRIPLE_CLICKED
    MIDDLE_PRESSED: int = curses.BUTTON3_PRESSED
    MIDDLE_CLICKED: int = curses.BUTTON3_CLICKED
    MIDDLE_DOUBLE_CLICKED: int = curses.BUTTON3_DOUBLE_CLICKED
    MIDDLE_TRIPLE_CLICKED: int = curses.BUTTON3_TRIPLE_CLICKED
    
    DRAGING: int = curses.REPORT_MOUSE_POSITION
    UNKNOWN: int = -1